[package]
name = "elements-verify-block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elements = "0.21.1"
hex = "0.4.3"
secp256k1 = "0.26.0"
