[package]
name = "elements-verify-block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.2"
elements = "0.21.1"
miniscript = "9.0.1"
